### ISSUE TITLE
Problem with Login for docker

### ISSUE THREAD

**Issue by mark-robustelli** [FusionAuth/fusionauth-example-anonymous-user#1]
When I try to go to login page, I get the following error.

A FreeMarker exception occurred. See the FusionAuth Event Log for additional details.

Blamed expression: –
Line number: 114
Column number: 7
End column number: 252
Theme Id: ed43c979-8b5e-4c64-9cfc-d1fff7b9cebd
Template name: /oauth2/authorize.ftl

Message:
Macro "alternativeLogins" has no parameter with name "federatedCSRFToken". Valid parameter names are: clientId, identityProviders, passwordlessEnabled, bootstrapWebauthnEnabled, idpRedirectState

![Screenshot 2023-09-13 at 1 25 36 PM](https://github.com/FusionAuth/fusionauth-example-anonymous-user/assets/137117976/27c44669-ffc5-42d8-8c6f-92f31f688b3d)

**Comment by mooreds** [comment]
@mark-robustelli I'm not able to recreate. Here were my replication steps:

```
mkdir test;
cd test
git clone git@github.com:FusionAuth/fusionauth-example-anonymous-user.git
cd fusionauth-example-anonymous-user
docker compose up -d
cd complete-application
python -m venv venv && source venv/bin/activate && pip install -r requirements.txt
flask --app server.py run
```

Then I visited localhost:5000 and clicked the login button.

Can you please share your replication steps? I know this is an issue with a certain version of FusionAuth with templates you upgrade (mentioned here: https://fusionauth.io/docs/v1/tech/release-notes#version-1-47-0 ), but that shouldn't apply in this case.

**Comment by mark-robustelli** [comment]
It was when I tried to visit http://localhost:9011.  I should have been more clear.  You never say to visit that in the guide, but I did.

**Comment by mark-robustelli** [comment]
Turns out the docker image was running an old version.  

Ran: `docker pull fusionauth/fusionauth-app` to get latest version and it fixed the issue.
